[feat] 해시태그 관련 기능 구현
qp-official-org/QP_BACKEND pull request #34
Opened 2024-01-20 12:50 UTC by msk226

## PR type
- [ ] Bug fix
- [ ] Feature
- [ ] Refactor
- [ ] Chore

## 💻 작업사항

- 작업사항 1 : 해시태그 관련 기능 구현 (생성, 삭제, 조회)

## ✔️ check list

- [ ] 작성한 이슈의 내용을 전부 적용했나요?
- [ ] 리뷰어를 등록했나요?

2024-01-20 15:28 UTC, Jinho622 commented on src/main/java/qp/official/qp/apiPayload/code/status/ErrorStatus.java
6001번 에러코드가 중복되는 것 같습니다. 35번째 줄은 지워주셔야 될 것 같아요!
그리고 36번째 줄의 "해시태그 요청이 비어있습니다."에 해당하는 enum이름을 HASHTAG_NOT_EXIST로 하고 38번째 줄의 "해당 해시태그가 존재하지 않습니다."에 해당하는 enum이름을 HASHTAG_NOT_FOUND로 바꿔야 워크북 내용처럼 좀 더 직관적일 것 같습니다!

2024-01-21 05:40 UTC, Leewonchan14 commented on src/main/java/qp/official/qp/web/controller/HashtagController.java
> +    public ApiResponse<HashtagResponseDTO.HashtagReturnDTO> deleteHashtag(@RequestBody HashtagRequestDTO.HashtagDTO request, @PathVariable Long hashtagId){
이거는 API 명세서랑 다른거 같은데요?

2024-01-21 06:14 UTC, Leewonchan14 requested changes
QueryService, CommandService 나누어서 작성해 주세요

2024-01-21 15:20 UTC, msk226 commented
> QueryService, CommandService 나누어서 작성해 주세요

수정했습니다.

2024-01-21 15:21 UTC, msk226 commented on src/main/java/qp/official/qp/apiPayload/code/status/ErrorStatus.java
> 6001번 에러코드가 중복되는 것 같습니다. 35번째 줄은 지워주셔야 될 것 같아요! 그리고 36번째 줄의 "해시태그 요청이 비어있습니다."에 해당하는 enum이름을 HASHTAG_NOT_EXIST로 하고 38번째 줄의 "해당 해시태그가 존재하지 않습니다."에 해당하는 enum이름을 HASHTAG_NOT_FOUND로 바꿔야 워크북 내용처럼 좀 더 직관적일 것 같습니다!

수정했습니다.

2024-01-22 03:51 UTC, Leewonchan14 approved these changes

2024-01-22 04:34 UTC, Jinho622 approved these changes

2024-01-22 04:34 UTC, merged